Add the --recover option to the annotate task
hoffmangroup/segway pull request #160
Opened 2022-01-27 17:05 UTC by EricR86

This is to address Issue #159.

Forcing a quit-out during annotate and using the recover option seems to work in a spot-check. It's believed this was removed accidentally during the interface change.

Also common options were now moved to a single source so the text relating to the options are no longer duplicated in code.

2022-02-14 20:29 UTC, EricR86 commented
@michaelmhoffman this is ready for your review

2022-03-03 18:22 UTC, michaelmhoffman requested changes
Approved after changes. If there's a reason not to do the `Argument.__init__()` like I suggested you can skip it, otherwise I think it would be a useful improvement.

2022-03-03 18:22 UTC, michaelmhoffman commented on segway/run.py
> +            "help" : "limit to genomic coordinates in" " FILE (default all)"
No space between `"help"` and `:` (this occurs multiple times.

2022-03-03 18:22 UTC, michaelmhoffman commented on segway/run.py
> +            "help" : "limit to genomic coordinates in" " FILE (default all)"
No point to having multiple strings on same line

2022-03-03 18:22 UTC, michaelmhoffman commented on segway/run.py
> +        def __init__(self, args, kwargs):
I would `def __init__(self, *args, **kwargs):`. Then you can do things like

```
include_coords_args = Argument("--include-coords",
                               metavar="FILE", help="limit to genomic coordinates)
```

where the interface is identical between use here or passing directly to `argparse.ArgumentParser.add_argument()`

2022-03-03 18:23 UTC, michaelmhoffman commented on segway/run.py
> +            "help" : "limit to genomic coordinates in" " FILE (default all)"
Changing `Argument.__init__()` as suggested would obviate the need for this.

2022-03-09 18:18 UTC, merged